set_attack_value(AT_EXTRA_2, AG_CATEGORY, 2);
set_attack_value(AT_EXTRA_2, AG_NUM_WINDOWS, 8);
set_attack_value(AT_EXTRA_2, AG_SPRITE, sprite_get("4flowmotion"));
set_attack_value(AT_EXTRA_2, AG_HURTBOX_SPRITE, sprite_get("4flowmotion_hurt"));

set_window_value(AT_EXTRA_2, 1, AG_WINDOW_TYPE, 9);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_LENGTH, 18);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(AT_EXTRA_2, 2, AG_WINDOW_LENGTH, 10);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_GOTO, 3);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_SFX, sound_get("final_dash"));
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_SFX_FRAME, 8);

set_window_value(AT_EXTRA_2, 3, AG_WINDOW_LENGTH, 16);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_GOTO, 8);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_VSPEED, -8);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(AT_EXTRA_2, 4, AG_WINDOW_LENGTH, 16);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_ANIM_FRAME_START, 12);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_GOTO, 8);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_HSPEED, 7);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_VSPEED, -4);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(AT_EXTRA_2, 5, AG_WINDOW_LENGTH, 16);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_ANIM_FRAME_START, 16);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_GOTO, 8);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_HSPEED, 8);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_VSPEED, 0);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(AT_EXTRA_2, 6, AG_WINDOW_LENGTH, 16);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_ANIM_FRAME_START, 20);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_GOTO, 8);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_HSPEED, 7);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_VSPEED, 4);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(AT_EXTRA_2, 7, AG_WINDOW_LENGTH, 16);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_ANIM_FRAME_START, 24);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_GOTO, 9);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_HSPEED, 0);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_VSPEED, 8);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(AT_EXTRA_2, 8, AG_WINDOW_TYPE, 7);
set_window_value(AT_EXTRA_2, 8, AG_WINDOW_LENGTH, 18);
set_window_value(AT_EXTRA_2, 8, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_EXTRA_2, 8, AG_WINDOW_ANIM_FRAME_START, 28);


set_num_hitboxes(AT_EXTRA_2, 5);

set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_WINDOW, 3);
set_hitbox_value(AT_EXTRA_2, 1, HG_LIFETIME, 8);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_X, 8);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_Y, -75);
set_hitbox_value(AT_EXTRA_2, 1, HG_WIDTH, 34);
set_hitbox_value(AT_EXTRA_2, 1, HG_HEIGHT, 90);
set_hitbox_value(AT_EXTRA_2, 1, HG_PRIORITY, 6);
set_hitbox_value(AT_EXTRA_2, 1, HG_DAMAGE, 5);
set_hitbox_value(AT_EXTRA_2, 1, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_2, 1, HG_ANGLE, 80);
set_hitbox_value(AT_EXTRA_2, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_2, 1, HG_KNOCKBACK_SCALING, 0.3);
set_hitbox_value(AT_EXTRA_2, 1, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_EXTRA_2, 1, HG_HIT_SFX, sound_get("OK_hitmedium2"));
set_hitbox_value(AT_EXTRA_2, 1, HG_VISUAL_EFFECT, hfx[4]);

set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_WINDOW, 4);
set_hitbox_value(AT_EXTRA_2, 2, HG_LIFETIME, 8);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_X, 70);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_2, 2, HG_WIDTH, 90);
set_hitbox_value(AT_EXTRA_2, 2, HG_HEIGHT, 40);
set_hitbox_value(AT_EXTRA_2, 2, HG_PRIORITY, 6);
set_hitbox_value(AT_EXTRA_2, 2, HG_DAMAGE, 5);
set_hitbox_value(AT_EXTRA_2, 2, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_ANGLE, 60);
set_hitbox_value(AT_EXTRA_2, 2, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_2, 2, HG_KNOCKBACK_SCALING, 0.3);
set_hitbox_value(AT_EXTRA_2, 2, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_EXTRA_2, 2, HG_HIT_SFX, sound_get("OK_hitmedium2"));
set_hitbox_value(AT_EXTRA_2, 2, HG_VISUAL_EFFECT, hfx[4]);

set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_WINDOW, 5);
set_hitbox_value(AT_EXTRA_2, 3, HG_LIFETIME, 8);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_X, 80);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_Y, -34);
set_hitbox_value(AT_EXTRA_2, 3, HG_WIDTH, 100);
set_hitbox_value(AT_EXTRA_2, 3, HG_HEIGHT, 34);
set_hitbox_value(AT_EXTRA_2, 3, HG_PRIORITY, 6);
set_hitbox_value(AT_EXTRA_2, 3, HG_DAMAGE, 5);
set_hitbox_value(AT_EXTRA_2, 3, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_2, 3, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_2, 3, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_2, 3, HG_KNOCKBACK_SCALING, 0.3);
set_hitbox_value(AT_EXTRA_2, 3, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_EXTRA_2, 3, HG_HIT_SFX, sound_get("OK_hitmedium2"));
set_hitbox_value(AT_EXTRA_2, 3, HG_VISUAL_EFFECT, hfx[4]);

set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_WINDOW, 6);
set_hitbox_value(AT_EXTRA_2, 4, HG_LIFETIME, 8);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_X, 56);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_Y, -18);
set_hitbox_value(AT_EXTRA_2, 4, HG_WIDTH, 90);
set_hitbox_value(AT_EXTRA_2, 4, HG_HEIGHT, 30);
set_hitbox_value(AT_EXTRA_2, 4, HG_PRIORITY, 6);
set_hitbox_value(AT_EXTRA_2, 4, HG_DAMAGE, 5);
set_hitbox_value(AT_EXTRA_2, 4, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_2, 4, HG_ANGLE, 40);
set_hitbox_value(AT_EXTRA_2, 4, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_2, 4, HG_KNOCKBACK_SCALING, 0.3);
set_hitbox_value(AT_EXTRA_2, 4, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_EXTRA_2, 4, HG_HIT_SFX, sound_get("OK_hitmedium2"));
set_hitbox_value(AT_EXTRA_2, 4, HG_VISUAL_EFFECT, hfx[4]);

set_hitbox_value(AT_EXTRA_2, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_WINDOW, 7);
set_hitbox_value(AT_EXTRA_2, 5, HG_LIFETIME, 8);
set_hitbox_value(AT_EXTRA_2, 5, HG_HITBOX_X, -12);
set_hitbox_value(AT_EXTRA_2, 5, HG_HITBOX_Y, 15);
set_hitbox_value(AT_EXTRA_2, 5, HG_WIDTH, 40);
set_hitbox_value(AT_EXTRA_2, 5, HG_HEIGHT, 90);
set_hitbox_value(AT_EXTRA_2, 5, HG_PRIORITY, 6);
set_hitbox_value(AT_EXTRA_2, 5, HG_DAMAGE, 5);
set_hitbox_value(AT_EXTRA_2, 5, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_2, 5, HG_ANGLE, 70);
set_hitbox_value(AT_EXTRA_2, 5, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_2, 5, HG_KNOCKBACK_SCALING, 0.3);
set_hitbox_value(AT_EXTRA_2, 5, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_EXTRA_2, 5, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_EXTRA_2, 5, HG_HIT_SFX, sound_get("OK_hitmedium2"));
set_hitbox_value(AT_EXTRA_2, 5, HG_VISUAL_EFFECT, hfx[4]);
